apiVersion: v1
kind: Service
metadata:
  name: main-model
  namespace: churn
  labels:
    app: main-model
spec:
  type: ClusterIP
  selector:
    app: main-model
  ports:
    - name: http
      port: 5000
      targetPort: 5000