apiVersion: v1
kind: Service
metadata:
  name: elector
  namespace: churn
  labels:
    app: elector
spec:
  type: LoadBalancer
  selector:
    app: elector
  ports:
    - name: http
      port: 80
      targetPort: 5002