apiVersion: v1
kind: Service
metadata:
  name: elector
  namespace: churn
  labels:
    app: elector
spec:
  type: LoadBalancer
  # loadBalancerSourceRanges:
  #   - 0.0.0.0/0 # Replace with your IP CIDR (e.g., 203.0.113.5/32)
  selector:
    app: elector
  ports:
    - name: http
      port: 80
      targetPort: 8501